# Generated by Django 4.2 on 2023-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Produce", "Produce"),
                            ("Dairy and Eggs", "Dairy and Eggs"),
                            ("Meat and Seafood", "Meat and Seafood"),
                            ("Bakery", "Bakery"),
                            ("Pantry Staples", "Pantry Staples"),
                            ("Frozen Foods", "Frozen Foods"),
                            ("Beverages", "Beverages"),
                            ("Snacks", "Snacks"),
                            ("Canned and Jarred Goods", "Canned and Jarred Goods"),
                            ("Condiments", "Condiments"),
                            ("Spices and Seasonings", "Spices and Seasonings"),
                            ("Deli and Prepared Foods", "Deli and Prepared Foods"),
                            (
                                "Household and Cleaning Supplies",
                                "Household and Cleaning Supplies",
                            ),
                            ("Baby and Child Care", "Baby and Child Care"),
                            ("Health and Wellness", "Health and Wellness"),
                            ("Pet Supplies", "Pet Supplies"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
