# Generated by Django 4.2 on 2023-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
