# Generated by Django 4.2 on 2023-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="street_address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
